### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by jason-tung** [DenChen11214/MilkThenCereal#2]
Starburst charts feel super engaging since you can better visualize the entering subsets of data and just hovering should make it intuitive. I would say this is a very compelling way to visualize the dataset you have chosen because it's an uncommon, organized way to visualize hierarchical data.

I do have to say, though, that rather than simply not encouraging me to explore data, I feel like it's not interactive enough to even prompt any exploration.

Solution: Add more user interactivity that affects how one could view the dataset like maybe trends or something.

**Comment by DenChen11214** [comment]
We believe that the customizable bar graphs will allow users to explore trends that they believe may exist. If the user wanted to see if there was a trend between critic scores and sales, then they could set the bar graph axes to those categories and decide for themselves based on the data if there is a trend or not.
