### ISSUE TITLE
rev_B

### ISSUE THREAD

**Issue by jason-tung** [DenChen11214/MilkThenCereal#3]
It seems clear what you intend to create: a starburst chart which allows users to visualize videogame data at each level (games, genres, consoles, etc.). 

I am, however, confused as to how you will provide the users with analytics on the data because you mention in under **How We Make This Data Come Alive**:

> “How do the sales of this game in North America compare to the sales of the game in Europe?” or “What genre has, on average, the most amount of sales?” 

But you don't show it in your sketch-up.

**Comment by DenChen11214** [comment]
We mentioned in **How We Make This Data Come Alive** that we will also include customizable bar graphs that the user can change the axes of, which will allow them to explore questions like the ones above. We did, however, not show it in our sketch-up and understand the confusion, but it will be implemented in the final product.
