### ISSUE TITLE
rev_D

### ISSUE THREAD

**Issue by ecrystale** [DenChen11214/MilkThenCereal#5]
I don't really see modifications that are needed other than perhaps it would be better for the bar graph to display the bars side by side rather than on top of each other. However, a possible feature to improve user interaction is to have an option to create more than one graph, maybe with different axes as well.

**Comment by DenChen11214** [comment]
We agree that it would be better to have the bar graphs side by side and have a legend with the countries as the keys. We will keep in mind the idea of having the option to create more than one graph and may implement it if time allows.
