### ISSUE TITLE
rev_C

### ISSUE THREAD

**Issue by tinawong15** [DenChen11214/MilkThenCereal#6]
Your chosen display format is appropriate for your chosen data. The pie chart is very clear and seems to have many options to allow users to compare between many different aspects, such as genre and publisher. However, you might also consider using a bar graph to show the difference in NA, EU, and Japan sales over time, because you have columns on that and the release year.

**Comment by DenChen11214** [comment]
Unfortunately, I don't think this will be possible, because the data only gives the total amount of sales in each nation as a whole and doesn't list the sales for each year.
