### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by tinawong15** [DenChen11214/MilkThenCereal#7]
It is clear how a user will interact with the data. The user will choose categories, which will change what is displayed on the pie chart and subsequent graphs. Some more user interactivity may help with encouraging the user to explore more though, such as getting the exact values when hovering over the bars on the bar chart.

**Comment by DenChen11214** [comment]
In addition to allowing the user to choose categories for the pie chart, we also plan to allow the user to customize their own bar graphs, which we believe will encourage them to explore certain relationships that may or may not exist. We agree that getting exact values when hovering over the bars is a good way to encourage user interaction and will most likely implement it in our project.
