### ISSUE TITLE
rev_B

### ISSUE THREAD

**Issue by tinawong15** [DenChen11214/MilkThenCereal#8]
It is clear what you aim to create. It seems to answer the questions that you set out to find out in your How We Aim to Make This Data Come Alive section. It might be helpful to emphasize how your data visualization will allow the user to clearly see whether or not scores given by users or metacritics have to do with how well a game sells because currently the user/critic score is just a value that is displayed, instead of in a graph.

**Comment by DenChen11214** [comment]
We plan to allow the users to customize their own bar graphs, so if the users wanted to create a graph of sales vs Metacritic scores, then they could explore whether or not the score influenced the number of sales the game had.
